### ISSUE TITLE
Cannot build bee-code-interpreter

### ISSUE THREAD

**Issue by planetf1** [i-am-bee/bee-code-interpreter#10]
Attempt to build the top level Dockerfile (bee-code-interpreter) on either of
* Linux, x86_64 Fedora core 41, docker 27.3.1
* macOS, aarch64, podman 5.2.5

with version 0.0.27 ( 3d9cd1986a4928981daf1bb8b5f2ef599c3927f3 ) 👍 

```
podman build -t localhost/bee-code-interpreter:local .
```
ends in 
```
/src/submodules/bee-proto/gen/python/proto does not contain any element
Error: building at STEP "RUN poetry bundle venv --python=/usr/local/bin/python --only=main /venv": while running runtime: exit status 1
```
Or with docker it ends in

```
/src/submodules/bee-proto/gen/python/proto does not contain any element
```

**Comment by Tomas2D** [comment]
Resolved? @planetf1

**Comment by JanPokorny** [comment]
I have switched the git submodules to use a relative URL, so the checkout will now work for both HTTPS and SSH cloning.
