### ISSUE TITLE
Question : Run python code which has intermediate , final files as well as returns a value ??

### ISSUE THREAD

**Issue by yb-sid** [i-am-bee/bee-code-interpreter#11]
Hi , I was able to solve my previous query and am able to run the code-interpreter using minikube in my local WSL 2 environment. 

Currently the gRPC service accepts following : 

`grpcurl -d '{"source_code":"print(\"hello world\")"}' -plaintext -max-time 60 127.0.0.1:50051 code_interpreter.v1.CodeInterpreterService/Execute`

here , "source_code" is the code to be executed , I'm guessing the `-plaintext` refers to read it as a text file . 

the output is generated as : 

```
{
  "stdout": "hello world\n"
}
```

This works well for simple cases when no output is expected or intermediate / final files are written / updated by code. 

Could I be given some suggestions , on which files and code I should explore so I can make necessary changes to make it work with files as well as like an API to return output as well ?? 

I could maybe raise a PR as well ??

**Comment by MikeDepies** [comment]
I ended up forking to add some features I needed. But you can just have it write to a file for return value, and then download that file to see the 'return result'

**Comment by yb-sid** [comment]
Yes I would be forking the repo as well . 

I'm kinda new to working with rust and submodules . Not sure where to begin in this codebase . 
I understand there's a service layer and an executor layer , but beyond that I don't quite get system enough to start making changes . 

Any help or suggestion is appreciated !

**Comment by MikeDepies** [comment]
I would start by just getting a good understanding on the current implementation decisions. The service layer is really just an http server and a parallel grpc server. They delegate most of their work to other service files in the project. The service layer manages files created by the execution pods by storing the file contents with the hash as the key.

To get started:
You could add a method in the server(http and grpc) to allow support for downloading files from the service layer.

Would recommend using ai to help understand the rust project (fortunately its just a single rust file, and some other files used to configure the execution environment.

**Comment by yb-sid** [comment]
I've got it. Thank you @MikeDepies . 

`https://github.com/i-am-bee/bee-code-interpreter/blob/main/src/code_interpreter/services/kubernetes_code_executor.py`

I believe this python file is calling executor within a kubernetes pod. 
I've got something to start off. 

Open Source is awesome!
