### ISSUE TITLE
Error after running the run.sh file

### ISSUE THREAD

**Issue by aevo98765** [i-am-bee/bee-code-interpreter#4]
Issue with the local.yaml or my local config.

My approach:

Mac M1 machine

1) Clone the repo using the --recurse-submodules flag. 

2) Run the run.sh command.

![Screenshot 2024-10-16 at 15 03 11](https://github.com/user-attachments/assets/ef7fbd94-e320-4b72-8562-0e7aeb28314b)

**Comment by JanPokorny** [comment]
@aevo98765 What engine for Docker/Kubernetes are you using? What is the output of `kubectl get po`?

**Comment by aevo98765** [comment]
Hey @JanPokorny, I noticed that I needed to switch my k8 context back to rancher-desktop. This specific issue is resolved now. Thanks for your reply.
