### ISSUE TITLE
Failure to install

### ISSUE THREAD

**Issue by MikeDepies** [i-am-bee/bee-code-interpreter#8]
I'm attempting to set the bee code interpreter on a mac. I have rancher desktop installed, and ran the run.sh script. It fails while building.
When trying to `git clone --recurse-submodules` the repo, the submodules fail to clone. This appears to be the same with the download zip and tagged releases.

> bash ./scripts/run.sh
> [+] Building 3.1s (13/15)                                  docker:desktop-linux
>  => [internal] load build definition from Dockerfile                       0.0s
>  => => transferring dockerfile: 843B                                       0.0s
>  => [internal] load metadata for docker.io/library/python:3.12-slim        0.3s
>  => [internal] load metadata for docker.io/library/python:3.12             0.4s
>  => [internal] load .dockerignore                                          0.0s
>  => => transferring context: 165B                                          0.0s
>  => [builder 1/6] FROM docker.io/library/python:3.12@sha256:b52e97a85736b  0.0s
>  => [runtime 1/4] FROM docker.io/library/python:3.12-slim@sha256:032c5261  0.0s
>  => CACHED [runtime 2/4] RUN apt-get update &&    apt-get install --no-in  0.0s
>  => [internal] load build context                                          0.0s
>  => => transferring context: 1.94kB                                        0.0s
>  => CACHED [builder 2/6] RUN apt-get update &&    apt-get install --no-in  0.0s
>  => CACHED [builder 3/6] RUN pipx install poetry &&    pipx inject poetry  0.0s
>  => CACHED [builder 4/6] WORKDIR /src                                      0.0s
>  => CACHED [builder 5/6] COPY . .                                          0.0s
>  => ERROR [builder 6/6] RUN poetry bundle venv --python=/usr/local/bin/py  2.7s
> ------                                                                          
>  > [builder 6/6] RUN poetry bundle venv --python=/usr/local/bin/python --only=main /venv:                                                                       
> 0.164                                                                           
> 0.216   • Bundling bee-code-interpreter (0.0.25) into /venv                     
> 0.216   • Bundling bee-code-interpreter (0.0.25) into /venv: Creating a virtual environment using Python /usr/local/bin/python
> 0.376   • Bundling bee-code-interpreter (0.0.25) into /venv: Installing dependencies
> 2.546   • Bundling bee-code-interpreter (0.0.25) into /venv: Installing bee-code-interpreter (0.0.25)
> 2.548 
> 2.548 /src/submodules/bee-proto/gen/python/proto does not contain any element
> ------
> Dockerfile:11
> --------------------
>    9 |     WORKDIR /src
>   10 |     COPY . .
>   11 | >>> RUN poetry bundle venv --python=/usr/local/bin/python --only=main /venv
>   12 |     
>   13 |     FROM docker.io/python:${PYTHON_VERSION}-slim AS runtime
> --------------------
> ERROR: failed to solve: process "/bin/sh -c poetry bundle venv --python=/usr/local/bin/python --only=main /venv" did not complete successfully: exit code: 1

**Comment by Tomas2D** [comment]
It seems that you incorrectly cloned the repository. This has worked for me.

```bash
git clone --recurse-submodules git@github.com:i-am-bee/bee-code-interpreter.git
bash ./scripts/run.sh
```

**Comment by MikeDepies** [comment]
When I did the clone I got this error. I assume that the missing file is because the permission denied issue comes up.

> git clone --recurse-submodules https://github.com/i-am-bee/bee-code-interpreter.git
> Cloning into 'bee-code-interpreter'...
> remote: Enumerating objects: 619, done.
> remote: Counting objects: 100% (246/246), done.
> remote: Compressing objects: 100% (142/142), done.
> remote: Total 619 (delta 148), reused 170 (delta 91), pack-reused 373 (from 1)
> Receiving objects: 100% (619/619), 205.67 KiB | 2.67 MiB/s, done.
> Resolving deltas: 100% (337/337), done.
> Submodule 'submodules/bee-proto' (git@github.com:i-am-bee/bee-proto) registered for path 'submodules/bee-proto'
> Cloning into '/Users/michaeldepies/bee-code-interpreter/submodules/bee-proto'...
> The authenticity of host 'github.com (140.82.112.4)' can't be established.
> ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
> This key is not known by any other names.
> Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
> Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> fatal: clone of 'git@github.com:i-am-bee/bee-proto' into submodule path '/Users/michaeldepies/bee-code-interpreter/submodules/bee-proto' failed
> Failed to clone 'submodules/bee-proto'. Retry scheduled
> Cloning into '/Users/michaeldepies/bee-code-interpreter/submodules/bee-proto'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> fatal: clone of 'git@github.com:i-am-bee/bee-proto' into submodule path '/Users/michaeldepies/bee-code-interpreter/submodules/bee-proto' failed
> Failed to clone 'submodules/bee-proto' a second time, aborting

**Comment by Tomas2D** [comment]
@MikeDepies, you don't seem to have access to GitHub via SSH Key, but it is needed based on the error message If you look at .git/submodules` you can see that the `submodule` must be downloaded via SSH instead HTTP. 

So first, set up the credentials and then clone them again.

**Comment by Tomas2D** [comment]
This will not be needed once we finish https://github.com/i-am-bee/bee-code-interpreter/issues/8

**Comment by MikeDepies** [comment]
okay, I was able to get past that, but have now run into this timeout when creating the pods - any thoughts?

> serviceaccount "code-interpreter-sa" deleted
> role.rbac.authorization.k8s.io "pod-manager-role" deleted
> rolebinding.rbac.authorization.k8s.io "pod-manager-binding" deleted
> pod "code-interpreter-service" deleted
> serviceaccount/code-interpreter-sa created
> role.rbac.authorization.k8s.io/pod-manager-role created
> rolebinding.rbac.authorization.k8s.io/pod-manager-binding created
> pod/code-interpreter-service created
> error: timed out waiting for the condition on pods/code-interpreter-service
