### ISSUE TITLE
Unable to install rancher-desktop

### ISSUE THREAD

**Issue by yb-sid** [i-am-bee/bee-code-interpreter#9]
I get errors while installing rancher desktop: 

After this operation, 1335 MB of additional disk space will be used.
Ign:1 https://mirror.tspu.ru/opensuse/repositories/isv%3A/Rancher%3A/stable/deb ./ rancher-desktop 1.16.0-2.1
Ign:1 https://mirror.tspu.ru/opensuse/repositories/isv%3A/Rancher%3A/stable/deb ./ rancher-desktop 1.16.0-2.1
Ign:1 https://mirror.tspu.ru/opensuse/repositories/isv%3A/Rancher%3A/stable/deb ./ rancher-desktop 1.16.0-2.1
Err:1 https://mirror.tspu.ru/opensuse/repositories/isv%3A/Rancher%3A/stable/deb ./ rancher-desktop 1.16.0-2.1
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 193.106.132.11 443]
E: Failed to fetch https://mirror.tspu.ru/opensuse/repositories/isv%3A/Rancher%3A/stable/deb/amd64/rancher-desktop_1.16.0-2.1_amd64.deb  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 193.106.132.11 443]
E: Internal Error, ordering was unable to handle the media swap

I believe due to `ru` mirror

Can't even download AppImage
![image](https://github.com/user-attachments/assets/c2ad4898-b2b9-46e1-ac4d-034b9e0d57cc)

Any other way to install and run code-interpreter without `rancher-desktop`

**Comment by psschwei** [comment]
I believe all you need is a local kubernetes cluster, of which there are a number of options: kind, minikube, colima, etc.

Though what you will have to do is modify the run script load the container images onto the cluster after this line: https://github.com/i-am-bee/bee-code-interpreter/blob/7dc57fbc93a6b7ff7ec70c79f03f2e0c0b4a80f6/scripts/run.sh#L17

For example, with kind you would do

```
kind load docker-image localhost/bee-code-interpreter:local
kind load docker-image localhost/bee-code-executor:local
```

It's also probably worth opening an issue with Rancher Desktop on your inability to download their appimage: https://github.com/rancher-sandbox/rancher-desktop/issues

**Comment by Tomas2D** [comment]
Were you able to make it work? @yb-sid

**Comment by yb-sid** [comment]
Yes I'm good with it. 
Thanks for your response @psschwei
